services:
  - type: web
    name: django-todo-backend
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py migrate"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: SECRET_KEY
        value: your_secret_key
      - key: DATABASE_URL
        sync: false
      - key: DEBUG
        value: false